Insert into "User" ("Name","Password","Surname","Username","UserID","PermissionID") values ('Jiří','pwd','Hladík','hladiji2','0','2');
Insert into "User" ("Name","Password","Surname","Username","UserID","PermissionID") values ('John','mod1','Disqus','mod1','1','1');
Insert into "User" ("Name","Password","Surname","Username","UserID","PermissionID") values ('Gordon','user1','Freeman','user1','2','0');
Insert into "User" ("Name","Password","Surname","Username","UserID","PermissionID") values ('Jan','pwd','Ferkl','ferklja1','3','2');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('59','Lea','Thompson','1');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('57','Elisabeth','Shue','2');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('69','Bob','Gale','3');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('55','Robert','Downey Jr.','4');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('24','Tom','Holland','5');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('54','Jon','Favreau','6');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('48','Gwyneth','Paltrow','7');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('96','Stan','Lee','8');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('77','Robert','De Niro','9');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('33','Zac','Efron','10');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('36','Aubrey','Plaza','11');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('26','Zoey','Deutch','12');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('80','Al','Pacino','13');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('78','Joe','Pesci','14');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('81','Harvey','Keitel','15');
Insert into "Cast" ("Age","Name","Surname","CastID") values ('59','Michael','J. Fox','0');
Insert into "Genre" ("Name","GenreID") values ('Action','0');
Insert into "Genre" ("Name","GenreID") values ('Comedy','1');
Insert into "Genre" ("Name","GenreID") values ('Drama','2');
Insert into "Genre" ("Name","GenreID") values ('Fantasy','3');
Insert into "Genre" ("Name","GenreID") values ('Horror','4');
Insert into "Genre" ("Name","GenreID") values ('Mystery','5');
Insert into "Genre" ("Name","GenreID") values ('Romance','6');
Insert into "Genre" ("Name","GenreID") values ('Thriller','7');
Insert into "Genre" ("Name","GenreID") values ('Sci-fi','8');
Insert into "Genre" ("Name","GenreID") values ('Western','9');
Insert into "Genre" ("Name","GenreID") values ('Animation','10');
Insert into "Movie" ("Name","Releasedate","MovieID") values ('Back to the Future',to_date('03.07.85','DD.MM.RR'),'0');
Insert into "Movie" ("Name","Releasedate","MovieID") values ('Dolittle',to_date('17.01.20','DD.MM.RR'),'1');
Insert into "Movie" ("Name","Releasedate","MovieID") values ('Iron Man',to_date('14.04.08','DD.MM.RR'),'2');
Insert into "Movie" ("Name","Releasedate","MovieID") values ('Terminator',to_date('20.12.84','DD.MM.RR'),'3');
Insert into "Movie" ("Name","Releasedate","MovieID") values ('Dirty Grandpa',to_date('22.01.16','DD.MM.RR'),'4');
Insert into "Movie" ("Name","Releasedate","MovieID") values ('Irishman',to_date('27.09.19','DD.MM.RR'),'5');
Insert into "Permission" ("Privilege","PermissionID") values ('User','0');
Insert into "Permission" ("Privilege","PermissionID") values ('Moderator','1');
Insert into "Permission" ("Privilege","PermissionID") values ('Admin','2');